- https://www.rbhayes.org/main/ohio-obituary-index/[Ohio Obituary Index]
- https://acpl.lib.in.us/images/Documents/Gendocs/States/Ohio_SG-2022.pdf[Genalogy Center Ohio State Guide]

=== Median County, Ohio

- https://www.familysearch.org/en/wiki/Medina_County,_Ohio_Genealogy[FamilySearch wiki -> Medina County]
  - Note: Marriage records and probate date from 1818, but birth and death date to 1867.

- https://medinacoogs.org/[Medina County, Ohio, Genealogical Society]

- http://www.medinacountyhistoricalsociety.com/[Medina County, Ohio, Historical Society]
  * Its https://www.medinacoogs.org/MCGSResearchPolicy.php[Research Assitance page] explains:

____
The Medina County Genealogical Society is pleased to provide research for individuals seeking information about their ancestors who resided in Medina County, Ohio.  The following types of services are available upon written request with an initial payment of $10 required at the time of request:

Courthouse Records: Births (1867-1908), Deaths (1867-1908), Marriages (beginning 1818), wills, and divorce records.

Recorders Office: Land Records.

Library: Early county and township histories, obituaries, newspaper articles, civil war indexes, and tax records.

Cemetery: Tombstone Inscriptions, cemetery locations, photographs of tombstones.

Any additional fees will be invoiced billed to you.

Schedule of fees: $10 per hour plus additional charges for photocopies, certified copies, and postage. There is a charge of $10 for tombstone photographs with no limit of photographs in one cemetery. There will be a fee of $5 for each additional cemetery requested.

Checks are to be made out to the Society and sent to the address above.

Inquiries as to additional costs and services can be made prior to requesting research by submitting your inquiry to the Society including a self-addressed, stamped envelope for the reply or by contacting the Society at the e-mail address above.
____ 

Ohio Online FamilySearch books:

- https://www.familysearch.org/library/books/records/?navigation=&perpage=&page=1&sort=_score&search=history+of+medina+county&fulltext=1&bookmarks=0#title[Pioneer history of Medina County]

- https://www.familysearch.org/library/books/records/item/776053*history*of*medina*county?offset=3[History of Median County]
Other books:

*A Standard History of William County, Ohio*, by  Bowersox, Charles A

Medina County Historical Society, History of Medina County, (Fostoria, Ohio: Gray Print. Co., 1948). Online at FamilySearch Digital Library.
Sheffer, Josephine C. History of Medina County and Ohio: Containing a History of the State of Ohio, from Its Earliest Settlement to the Present Time,(Chicago, Illinois: Baskin & Battey, 1881). Online at FamilySearch Digital Library, Google Books, Internet Archive.
Northrop, Nira B., Pioneer History of Medina County, (Medina, Ohio: G. Redway, 1861). Online at FamilySearch Digital Library, Google Books, Internet Archive, Ancestry ($) * Indexed.


You may want to study local histories for areas such as the Maumee, Miami, Hocking, Muskingum, Scioto, and Mahoning Valleys.

Online Ohio Historical Society's https://digital*collections.columbuslibrary.org/digital/collection/genealogy/id/70300/[Surname Index].
Bibliography of Local Histories

=== Williams County Ohio

- FamilySearch digital copy of https://www.familysearch.org/library/books/viewer/797591/?offset=6#page=1&viewer=picture&o=&n=0&q=[County of Williams, Ohio, Historical and Biographical]
- https://www.familysearch.org/library/books/records/item/797591-county-of-williams-ohio-historical-and-biographical[Platt Book of Williams County, Ohio]

=== Defiance County Ohio

- https://www.familysearch.org/library/books/viewer/508162/?offset=&return=1#page=1&viewer=picture&o=&n=0&q=o[Defiance County, Ohio : a collection of historical sketches and family histories compiled by members and friends of the Defiance County Historical Society]
- https://www.familysearch.org/library/books/viewer/552536/?offset=&return=1#page=1&viewer=picture&o=&n=0&q=[History of Defiance County, Ohio : containing a history of the County ; its townships, towns, etc. ; military record ; portraits of early settlers and prominent men ]
- https://www.defiancecountygenealogy.org/[Defiance County, Ohio, Geneaological Society]
- https://www.ancestry.com/search/collections/7412/[Ancestry.com Defiance Democrate Newspaper Search]
- https://www.familysearch.org/library/books/viewer/536001/?offset=&return=1#page=1&viewer=picture&o=&n=0&q=o[Commemorative biographical record of northwestern Ohio : including the counties of Defiance, Henry, Williams, and Fulton]
- https://www.familysearch.org/library/books/viewer/224104/?offset=&return=1#page=2&viewer=picture&o=&n=0&q=[County by County in Ohio Genealogy], bibliography for each county
- https://www.familysearch.org/library/books/viewer/354705/?offset=&return=1#page=1&viewer=picture&o=&n=0&q=[Obituaries, Pioneeers of Northwest Ohio]
- https://www.defiance-county.com/engineer/maps.htm[Defiance County, Platt Books, Surveys, GIS webiste, etc]. Earliest Platt book is 1866 and shows *Goller* and *J.C. Vollmer*
- https://www.defiance-county.com/recorder/[Recorder's Office]
