=== FamilySearch wiki German Research Section

General:

The book *Finding Your German Ancestor's, A Beginner's Guide* by Kevan A Hansen is an exellent short inntroduction.

=== Schott List of German Research Resources

todo: Move these resources to the appropriate section.

*CompGen* https://www.compgen.de[CompGen]

*Meyers Gazetteer:* Online gazetteer of locations in the German Empire
(1871-1918), including maps and key information about civil and
religious jurisdictions. It’s a great resource for identifying where
your ancestor came from, and where the archives would be that might have
more records.

* http://www.meyersgaz.org[Meyer's Gazetteer]

*Kartenmeister:* Database of German place locations east of current-day
German borders. You can search by German or Polish name of the location.

* http://www.kartenmeister.com/preview/databaseuwe.asp[Kartenmeister]

*FamilySearch Wiki on Germany:* Great source of information on all
things related to genealogy in Germany. It’s also the best source to
identify the right state, local, and church archives that might have
additional information on your ancestors. Site includes contact
information (websites, email, postal address) and some form letters to
help you communicate in German.

* https://www.familysearch.org/en/wiki/Germany_Genealogy[German Genealogy]

* https://www.familysearch.org/en/wiki/Germany_Archives_and_Libraries[Archives and Libraries]

*Ortsippenbücher or Ortfamilienbücher:* These books focus on one
town/village, and are a compilation of all family data for people who
lived in that village, generally using church records as a source. Pro –
these are printed and easy to read and show all family connections. Con
– they’re transcribed from the original records, which creates the
possibility for error. But using these can help you more easily locate
your ancestors in the original records. Where to find these books:

* Purchase: Try eBay (www.ebay.com) or Abe Books (www.abebooks.com)
* Libraries: Worldcat (www.worldcat.org) can identify which libraries
have the one you’re searching for. Of course, many are in the Family
History Library (search Catalog at http://www.familysearch.org[http://www.familysearch.org]. The
St. Louis County Library also has a large collection
https://www.slcl.org/content/ortssippenb%C3%BCcher-familienb%C3%BCcher-held-history-and-genealogy-department[St. Louis County Public Library]
* Online at CompGen (aka Genealogy.net): Compgen has nearly 1,000 of
these books digitized and online https://ofb.genealogy.net/[Ortsippenbücher].

*CompGen aka Genealogy.net:* This is an association in Germany that has
provided online genealogy data since 1990. Site is in German; use Chrome
to translate. http://www.comgen.de Some of the key parts of this site
are:

* DigiBib (Digital Library): Digitized books such as directories,
government and church histories, etc.
http://wiki-de.genealogy.net/Portal:DigiBib or
http://www.digibib.genealogy.net/viewer/index/
* Networking: Includes ways to connect with others, including discussion
forums and how- to videos http://www.compgen.de/kommunizieren/
* Databases: Includes searchable databases that include gravestones, war
casualty lists, directories, individual members’ trees, etc.
http://www.compgen.de/recherchieren/#datenbanken
* GenWiki: Includes articles on many German genealogy-related topics
http://wiki- de.genealogy.net/Hauptseite
* Name distribution map: Enables you to map the primary locations your
surname was found in 1890 and 1996
http://www.compgen.de/recherchieren/#namenskarte

*Geogen:* This is another website to map locations where your surnames
are found, based on current-day information (directories). Provides
links to similar maps for nearby countries.

* Current version is 4: https://geogen.stoepel.net/
* Legacy version (with more functionality):
https://legacy.stoepel.net/en

*MyHeritage:* This is a commercial genealogy site that provides DNA
testing and some indexes and records. Although their record collection
is small compared to Ancestry or FamilySearch, it’s worth checking. It
is also the most popular DNA test in Europe, which may help you find
distant cousins in Europe.

* http://www.myheritage.com

*German Handwriting:* There’s no substitute for learning German
handwriting to help you in your research. But one helpful hint is to use
this online handwriting generator to see what the name or village you’re
searching for should look like, enabling you to scan records more
quickly.

=== Familienforschung Database

https://gedbas.genealogy.net/

=== Contacts in Germany

https:///www.vennekohl.de[Vennekohl.de]
 
file:///home/kurt/g/lectures/Expanding_Your_German_Research_Beyond_Ancestry_and_FamilySearch-handout.pdf[Expanding Your German Research Beyond Ancestry and FamilySearch]

=== German Verein Liste

GenWiki's link:https://wiki.genealogy.net/Portal:Vereine[Portal von Vereine]

____
Viele genealogische Vereine, Arbeitskreise, Interessengemeinschaften und andere genealogische Institute stellen sich auf dem Server des Vereins für Computergenealogie e.V. vor und nehmen aktiv an den Projekten teil.
Auch wenn Sie vielleicht sonst ein Vereinsmuffel sind, die Mitgliedschaft in einem genealogischen Verein kann sich lohnen! Viele genealogische Veranstaltungen werden von Vereinen ausgerichtet. Mitglieder einiger
Vereine, Arbeitsgruppen usw., die hier im GenWiki eine Anmeldung und damit eine Benutzerseite haben, teilen ihre Mitgliedschaft dort mit, die Übersicht dazu findet sich hier. 
____

Baden-Württemberg:

- link:https://www.vfkbw.de/[Verein für Familienkunde in Baden-Württemberg]

- https://www.verein.wuerttembergische-kirchengeschichte.de/[Verein für württembergische Landeskirche]

Hesse:

- link:https://www.hfv-ev.de/[Hessische familiengeschichtliche Vereinigung (HfV)]

=== Websites for Specific Areas

- https://www.aegilops.com/slp/index.html[Schaumburg-Lippe Genealogy]

- https://www.nhv-lippe.de/fileadmin/user_upload/Sonderver%C3%B6ffentlichungen/%C3%9Cbersicht_lieferbare_B%C3%A4nde_SV_Internet.pdf[Publications of the Naturwissenschaftlichen und
  HIstorischen Vereins für das Land Lipp e. V.]

=== Church Registers

*Archion:* does have a 20-day pass that allows you to pause and resume.

* http://www.archion.de/en/[Archion.de]

*Matricula:* Free service that provides online access to church records,
primarily Catholic. Also includes records from Austria, Luxemburg,
Slovenia. Again, may include records not available in Ancestry or
FamilySearch.

* https://data.matricula-online.eu/en/[Matricula]

Family Roots Publishing has a set of https://www.familyrootspublishing.com/search_results.php[Map Guides to Württemberg Parish Registers], one for each Landkreis (apparently). This includes The vollmer's
Landkreis of Donaukreis, in which their village, Owen, lay.

The Genealogy Center has thes Map Guides. In particular, for these kingdoms of interest to me:

- https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/896626?offset=0&qs=Grandduchy%20of%20Hessen%20Map%20Guide%20to%20German%20Parish%20Registers&search_in=iets&state=search[Map guide to German parish registers. Grandduchy of Hessen / by Kevan M. Hansen ; introduction by George Ott]

- https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/958020?offset=0&qs=W%C3%BCrttemberg%20%20Donaukreis%20Map%20Guide%20to%20German%20Parish%20Registers&search_in=iets&state=search[Map guide to German parish registers. Kingdom of Württemberg, volume IV Donaukreis, with full index of included towns and master index to Württemberg, volumes I to IV / by Kevan M. Hansen with introduction by George Ott]

- If needed, get url for volume for northern germany near minden, etc. 

=== Wuerttemberg

Württemberg has a lot of research sites because they kept more family data than other kingdoms. The Family Search wiki's
https://www.familysearch.org/en/wiki/W%C3%BCrttemberg,_German_Empire_Genealogy[Württemberg, German Empire Genealogy] has numerous links to them.

Ancestry describes the https://www.ancestry.com/search/collections/61389/[About Württemberg, Germany, Family Tables, 1550-1985]:

____
What you can find in the records

Beginning in 1808, family tables were extensively recorded in Württemberg and supplement parish records. Three generations of a family are usually recorded on a single or double-page sheet. Each record begins with the male head of household. The family tables are generally arranged alphabetically according to the first letter of the family surname. Depending on the time period and on the individual forms used, you may generally find the following details in these records:

Head of household, Father: Last Name, Given names, Occupation, Birthdate, Marriage Date, Death Date, details about his Parents
Mother: Last Name, Maiden Name, Given names, Birthdate, Marriage Date, Death Date, details about her Parents
Children: Last Name, Given names, Occupation, Birthdate, Confirmation or Communion, Marriage Date, details about Spouse, Death Date, often includes children born outside of or previous to the marriage.
More about using this collection

This collection is based on older microfilms. Under "Browse this collection,” select the City or District and then the Description and Year Range for the desired records.
____

=== Hesse

include::./hesse.adoc[]

=== Niedersachsen/Schaumburg

include::./niedersachsen.adoc[]

=== Baden Wuerttemberg

include::./baden-wuerttemberg.adoc[]

=== 

include::./nrw.adoc[]
