==== Niedersachsen Sources

- https://www.familienkunde-niedersachsen.de/[Familienkund Nidersachsen]
- https://www.familysearch.org/de/wiki/Niedersachsen_Genealogie [FamilySearch:German Version:Nidersachsen Genealogie]
- https://nla.niedersachsen.de/startseite/benutzung/nutzliche_hilfsmittel/-85855.html[Niedersächsisches Landesarchiv:Guide to Family Research:German] 	 
- https://forum.ahnenforschung.net/forumdisplay.php?f=20[Niedersachsen Genealogie Forunm ]
- https://www.facebook.com/Niedersaechsischer.Landesverein.fuer.Familienkunde/[Familienkunde Niedersachsen Facebook Page]
- http://www.westpreussen.de/[Familenforschung in Westpreußen]
- https://wiki.genealogy.net/Nieders%C3%A4chsischer_Landesverein_f%C3%BCr_Familienkunde_e.V._(NLF[Niedersächsicher Landesverein für Familenkunde]

==== Schaumburg-Lippe Kirchenbücher

Kirchenbücher der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe haben auf Archion zur Verfügung gestellt. Das heiß, dass man die Kirchenbücher für die folgende Städte: 

- Altenhagen-Hagenburg
- Bergkirchen
- Bückeburg
- Frille
- Heuerßen
- Lauenhagen
- Lindhorst
- Meerbeck
- Meinsen
- Petzen
- Probsthagen
- Stadthagen
- Steinbergen
- Steinhude
- Sülbeck
- Vehlen

`Browse > Niedersachsen: Niedersächsisches Landesarchiv > Kirchenbücher der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe > Petzen`

permalink to http://www.archion.de/p/5818cf1a1c/[Niedersachsen: Niedersächsisches Landesarchiv > Kirchenbücher der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe > Petzen > Verzeichnis der Getauften, Konfirmierten, Getrauten und Gestorbenen 1785-1827]

Note: I believe that **Niedersachsen: Landeskirchliches Archiv Hannover -> Kirchenkreis Holzminden** is not yet in green, meaning it is not vailable (as of 09/12/2022).
